name: Bump version

on:
  # push:
  #   branches:
  #     - main

jobs:
  build:
    
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      id: tag_version
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        PRERELEASE: true 

    - name: Set tag version as an output
      run: echo "TAG_VERSION=${{ steps.tag_version.outputs.tag }}" >> $GITHUB_ENV

    - name: Login to DockerHUB
      run: |
        docker login -u ${{ secrets.DOCKER_USER }} --password-stdin <<< ${{ secrets.DOCKER_PASS }}

    - name: Build and Tag Docker Image
      run: |
          version=$TAG_VERSION
          docker build -t ${{ secrets.DOCKER_USER }}/tacoshop:${version} .
          docker tag ${{ secrets.DOCKER_USER }}/tacoshop:${version} ${{ secrets.DOCKER_USER }}/tacoshop:latest
  
    - name: Push Image to DockerHUB
      run: |
          version=$TAG_VERSION
          docker push ${{ secrets.DOCKER_USER }}/tacoshop:${version}
        #   docker push ${{ secrets.DOCKER_USER }}/tacoshop
    
    - name: Pull New Image to Server
      uses: appleboy/ssh-action@master
      with:
        host: 146.190.26.15
        username: "root"
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          docker login -u ${{ secrets.DOCKER_USER }} --password-stdin <<< ${{ secrets.DOCKER_PASS }}
          docker pull biighunter/tacoshop:${{ steps.tag_version.outputs.tag }}

    - name: Add The New Tag to .env For Taco.yaml File
      uses: appleboy/ssh-action@master
      with:
        host: 146.190.26.15
        username: "root"
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /root/K8s-Taco
          rm -rf .env
          echo "TACO_VERSION=${{ steps.tag_version.outputs.tag }}" >> .env
          cat .
          chmod 777 -R .env
          kubectl apply -f taco.yaml